/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class actions_scheduleStore : Meridian.IEntityStore, admin.db.IDataService<proto.actions_schedule>
	{
		public actions_scheduleStore()
		{
			m_Items = new SortedList<long, proto.actions_schedule>();
		}
		private SortedList<long, proto.actions_schedule> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.actions_schedule> GetAll()
		{
			return Queryable.AsQueryable<proto.actions_schedule>(All());
		}
		public proto.actions_schedule GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.actions_schedule>.Insert(proto.actions_schedule item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.actions_schedule>.Delete(proto.actions_schedule item)
		{
			Delete(item);
		}
		public proto.actions_schedule CreateItem()
		{
			return new proto.actions_schedule() {   };
		}
		public void AbortItem(proto.actions_schedule item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.actions_schedule>.Update(proto.actions_schedule item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.actions_schedule);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `action_place_id`, `datetime` FROM actions_schedule");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.actions_schedule();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.actions_schedule Insert(MySqlConnection _connection, proto.actions_schedule _item)
		{
			var cmd = new MySqlCommand("INSERT INTO actions_schedule ( `action_place_id`, `datetime` ) VALUES ( @action_place_id, @datetime ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "action_place_id", Value = _item.action_place_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "datetime", Value = (_item.datetime != null && _item.datetime.Year > 1800) ? _item.datetime : new DateTime(1800, 1, 1) });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.actions_schedule Update(MySqlConnection _connection, proto.actions_schedule _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE actions_schedule SET `action_place_id`= @action_place_id, `datetime`= @datetime WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_action_place_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "action_place_id = @action_place_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "action_place_id", Value = _item.action_place_id });
			}
			if(_item.mc_datetime)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "datetime = @datetime";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "datetime", Value = _item.datetime });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE actions_schedule SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.actions_schedule Delete(MySqlConnection _connection, proto.actions_schedule _item)
		{
			var cmd = new MySqlCommand("DELETE FROM actions_schedule WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.actions_schedule Insert(proto.actions_schedule _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.actions_schedule Persist(proto.actions_schedule _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.actions_schedule Delete(proto.actions_schedule _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.actions_schedule Update(proto.actions_schedule _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.actions_schedule> All()
		{
			return m_Items.Values;
		}
		public proto.actions_schedule Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `action_place_id`, `datetime` FROM actions_schedule WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `action_place_id`, `datetime` FROM actions_schedule WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.actions_schedule();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
