/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class blog_marksStore : Meridian.IEntityStore, admin.db.IDataService<proto.blog_marks>
	{
		public blog_marksStore()
		{
			m_Items = new SortedList<long, proto.blog_marks>();
		}
		private SortedList<long, proto.blog_marks> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.blog_marks> GetAll()
		{
			return Queryable.AsQueryable<proto.blog_marks>(All());
		}
		public proto.blog_marks GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.blog_marks>.Insert(proto.blog_marks item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.blog_marks>.Delete(proto.blog_marks item)
		{
			Delete(item);
		}
		public proto.blog_marks CreateItem()
		{
			return new proto.blog_marks() {   };
		}
		public void AbortItem(proto.blog_marks item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.blog_marks>.Update(proto.blog_marks item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.blog_marks);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `blog_id`, `mark`, `create_date` FROM blog_marks");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.blog_marks();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.blog_marks Insert(MySqlConnection _connection, proto.blog_marks _item)
		{
			var cmd = new MySqlCommand("INSERT INTO blog_marks ( `account_id`, `blog_id`, `mark`, `create_date` ) VALUES ( @account_id, @blog_id, @mark, @create_date ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "blog_id", Value = _item.blog_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "mark", Value = _item.mark });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "create_date", Value = (_item.create_date != null && _item.create_date.Year > 1800) ? _item.create_date : new DateTime(1800, 1, 1) });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.blog_marks Update(MySqlConnection _connection, proto.blog_marks _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE blog_marks SET `account_id`= @account_id, `blog_id`= @blog_id, `mark`= @mark, `create_date`= @create_date WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_account_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "account_id = @account_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			}
			if(_item.mc_blog_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "blog_id = @blog_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "blog_id", Value = _item.blog_id });
			}
			if(_item.mc_mark)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "mark = @mark";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "mark", Value = _item.mark });
			}
			if(_item.mc_create_date)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "create_date = @create_date";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "create_date", Value = _item.create_date });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE blog_marks SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.blog_marks Delete(MySqlConnection _connection, proto.blog_marks _item)
		{
			var cmd = new MySqlCommand("DELETE FROM blog_marks WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.blog_marks Insert(proto.blog_marks _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.blog_marks Persist(proto.blog_marks _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.blog_marks Delete(proto.blog_marks _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.blog_marks Update(proto.blog_marks _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.blog_marks> All()
		{
			return m_Items.Values;
		}
		public proto.blog_marks Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `blog_id`, `mark`, `create_date` FROM blog_marks WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `blog_id`, `mark`, `create_date` FROM blog_marks WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.blog_marks();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
