/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class company_photosStore : Meridian.IEntityStore, admin.db.IDataService<proto.company_photos>
	{
		public company_photosStore()
		{
			m_Items = new SortedList<long, proto.company_photos>();
		}
		private SortedList<long, proto.company_photos> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.company_photos> GetAll()
		{
			return Queryable.AsQueryable<proto.company_photos>(All());
		}
		public proto.company_photos GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.company_photos>.Insert(proto.company_photos item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.company_photos>.Delete(proto.company_photos item)
		{
			Delete(item);
		}
		public proto.company_photos CreateItem()
		{
			return new proto.company_photos() {   };
		}
		public void AbortItem(proto.company_photos item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.company_photos>.Update(proto.company_photos item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.company_photos);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `thumbnaill`, `normal`, `is_main`, `company_id` FROM company_photos");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.company_photos();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.company_photos Insert(MySqlConnection _connection, proto.company_photos _item)
		{
			var cmd = new MySqlCommand("INSERT INTO company_photos ( `thumbnaill`, `normal`, `is_main`, `company_id` ) VALUES ( @thumbnaill, @normal, @is_main, @company_id ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnaill", Value = _item.thumbnaill });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "normal", Value = _item.normal });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_main", Value = _item.is_main });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "company_id", Value = _item.company_id });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.company_photos Update(MySqlConnection _connection, proto.company_photos _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE company_photos SET `thumbnaill`= @thumbnaill, `normal`= @normal, `is_main`= @is_main, `company_id`= @company_id WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_thumbnaill)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "thumbnaill = @thumbnaill";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "thumbnaill", Value = _item.thumbnaill != null ? (object)_item.thumbnaill : DBNull.Value });
			}
			if(_item.mc_normal)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "normal = @normal";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "normal", Value = _item.normal != null ? (object)_item.normal : DBNull.Value });
			}
			if(_item.mc_is_main)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "is_main = @is_main";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "is_main", Value = _item.is_main });
			}
			if(_item.mc_company_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "company_id = @company_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "company_id", Value = _item.company_id });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE company_photos SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.company_photos Delete(MySqlConnection _connection, proto.company_photos _item)
		{
			var cmd = new MySqlCommand("DELETE FROM company_photos WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.company_photos Insert(proto.company_photos _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.company_photos Persist(proto.company_photos _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.company_photos Delete(proto.company_photos _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.company_photos Update(proto.company_photos _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.company_photos> All()
		{
			return m_Items.Values;
		}
		public proto.company_photos Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `thumbnaill`, `normal`, `is_main`, `company_id` FROM company_photos WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `thumbnaill`, `normal`, `is_main`, `company_id` FROM company_photos WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.company_photos();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
