/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class pagesStore : Meridian.IEntityStore, admin.db.IDataService<proto.pages>
	{
		public pagesStore()
		{
			m_Items = new SortedList<long, proto.pages>();
		}
		private SortedList<long, proto.pages> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.pages> GetAll()
		{
			return Queryable.AsQueryable<proto.pages>(All());
		}
		public proto.pages GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.pages>.Insert(proto.pages item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.pages>.Delete(proto.pages item)
		{
			Delete(item);
		}
		public proto.pages CreateItem()
		{
			return new proto.pages() {   };
		}
		public void AbortItem(proto.pages item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.pages>.Update(proto.pages item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.pages);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `title`, `publish_date`, `html`, `user_id`, `alias` FROM pages");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.pages();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.pages Insert(MySqlConnection _connection, proto.pages _item)
		{
			var cmd = new MySqlCommand("INSERT INTO pages ( `title`, `publish_date`, `html`, `user_id`, `alias` ) VALUES ( @title, @publish_date, @html, @user_id, @alias ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "publish_date", Value = (_item.publish_date != null && _item.publish_date.Year > 1800) ? _item.publish_date : new DateTime(1800, 1, 1) });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "html", Value = _item.html });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "user_id", Value = _item.user_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "alias", Value = _item.alias });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.pages Update(MySqlConnection _connection, proto.pages _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE pages SET `title`= @title, `publish_date`= @publish_date, `html`= @html, `user_id`= @user_id, `alias`= @alias WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "title = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_publish_date)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "publish_date = @publish_date";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "publish_date", Value = _item.publish_date });
			}
			if(_item.mc_html)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "html = @html";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "html", Value = _item.html != null ? (object)_item.html : DBNull.Value });
			}
			if(_item.mc_user_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "user_id = @user_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "user_id", Value = _item.user_id });
			}
			if(_item.mc_alias)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "alias = @alias";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "alias", Value = _item.alias != null ? (object)_item.alias : DBNull.Value });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE pages SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.pages Delete(MySqlConnection _connection, proto.pages _item)
		{
			var cmd = new MySqlCommand("DELETE FROM pages WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.pages Insert(proto.pages _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.pages Persist(proto.pages _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.pages Delete(proto.pages _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.pages Update(proto.pages _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.pages> All()
		{
			return m_Items.Values;
		}
		public proto.pages Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `title`, `publish_date`, `html`, `user_id`, `alias` FROM pages WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `title`, `publish_date`, `html`, `user_id`, `alias` FROM pages WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.pages();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
