/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class photobank_photo_pricesStore : Meridian.IEntityStore, admin.db.IDataService<proto.photobank_photo_prices>
	{
		public photobank_photo_pricesStore()
		{
			m_Items = new SortedList<long, proto.photobank_photo_prices>();
		}
		private SortedList<long, proto.photobank_photo_prices> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.photobank_photo_prices> GetAll()
		{
			return Queryable.AsQueryable<proto.photobank_photo_prices>(All());
		}
		public proto.photobank_photo_prices GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.photobank_photo_prices>.Insert(proto.photobank_photo_prices item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.photobank_photo_prices>.Delete(proto.photobank_photo_prices item)
		{
			Delete(item);
		}
		public proto.photobank_photo_prices CreateItem()
		{
			return new proto.photobank_photo_prices() {   };
		}
		public void AbortItem(proto.photobank_photo_prices item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.photobank_photo_prices>.Update(proto.photobank_photo_prices item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.photobank_photo_prices);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `rel_photo_id`, `license_id`, `price` FROM photobank_photo_prices");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_photo_prices();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.photobank_photo_prices Insert(MySqlConnection _connection, proto.photobank_photo_prices _item)
		{
			var cmd = new MySqlCommand("INSERT INTO photobank_photo_prices ( `rel_photo_id`, `license_id`, `price` ) VALUES ( @rel_photo_id, @license_id, @price ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "rel_photo_id", Value = _item.rel_photo_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "license_id", Value = _item.license_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price", Value = _item.price });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.photobank_photo_prices Update(MySqlConnection _connection, proto.photobank_photo_prices _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE photobank_photo_prices SET `rel_photo_id`= @rel_photo_id, `license_id`= @license_id, `price`= @price WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_rel_photo_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "rel_photo_id = @rel_photo_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "rel_photo_id", Value = _item.rel_photo_id });
			}
			if(_item.mc_license_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "license_id = @license_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "license_id", Value = _item.license_id });
			}
			if(_item.mc_price)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "price = @price";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price", Value = _item.price });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE photobank_photo_prices SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.photobank_photo_prices Delete(MySqlConnection _connection, proto.photobank_photo_prices _item)
		{
			var cmd = new MySqlCommand("DELETE FROM photobank_photo_prices WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.photobank_photo_prices Insert(proto.photobank_photo_prices _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.photobank_photo_prices Persist(proto.photobank_photo_prices _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.photobank_photo_prices Delete(proto.photobank_photo_prices _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.photobank_photo_prices Update(proto.photobank_photo_prices _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.photobank_photo_prices> All()
		{
			return m_Items.Values;
		}
		public proto.photobank_photo_prices Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `rel_photo_id`, `license_id`, `price` FROM photobank_photo_prices WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `rel_photo_id`, `license_id`, `price` FROM photobank_photo_prices WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_photo_prices();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
