/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class photobank_obtainedStore : Meridian.IEntityStore, admin.db.IDataService<proto.photobank_obtained>
	{
		public photobank_obtainedStore()
		{
			m_Items = new SortedList<long, proto.photobank_obtained>();
		}
		private SortedList<long, proto.photobank_obtained> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.photobank_obtained> GetAll()
		{
			return Queryable.AsQueryable<proto.photobank_obtained>(All());
		}
		public proto.photobank_obtained GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.photobank_obtained>.Insert(proto.photobank_obtained item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.photobank_obtained>.Delete(proto.photobank_obtained item)
		{
			Delete(item);
		}
		public proto.photobank_obtained CreateItem()
		{
			return new proto.photobank_obtained() {   };
		}
		public void AbortItem(proto.photobank_obtained item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.photobank_obtained>.Update(proto.photobank_obtained item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.photobank_obtained);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `price_id`, `buy_date` FROM photobank_obtained");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_obtained();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.photobank_obtained Insert(MySqlConnection _connection, proto.photobank_obtained _item)
		{
			var cmd = new MySqlCommand("INSERT INTO photobank_obtained ( `account_id`, `price_id`, `buy_date` ) VALUES ( @account_id, @price_id, @buy_date ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price_id", Value = _item.price_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "buy_date", Value = (_item.buy_date != null && _item.buy_date.Year > 1800) ? _item.buy_date : new DateTime(1800, 1, 1) });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.photobank_obtained Update(MySqlConnection _connection, proto.photobank_obtained _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE photobank_obtained SET `account_id`= @account_id, `price_id`= @price_id, `buy_date`= @buy_date WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_account_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "account_id = @account_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			}
			if(_item.mc_price_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "price_id = @price_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "price_id", Value = _item.price_id });
			}
			if(_item.mc_buy_date)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "buy_date = @buy_date";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "buy_date", Value = _item.buy_date });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE photobank_obtained SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.photobank_obtained Delete(MySqlConnection _connection, proto.photobank_obtained _item)
		{
			var cmd = new MySqlCommand("DELETE FROM photobank_obtained WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.photobank_obtained Insert(proto.photobank_obtained _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.photobank_obtained Persist(proto.photobank_obtained _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.photobank_obtained Delete(proto.photobank_obtained _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.photobank_obtained Update(proto.photobank_obtained _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.photobank_obtained> All()
		{
			return m_Items.Values;
		}
		public proto.photobank_obtained Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `price_id`, `buy_date` FROM photobank_obtained WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `price_id`, `buy_date` FROM photobank_obtained WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_obtained();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
