/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class photobank_user_albumsStore : Meridian.IEntityStore, admin.db.IDataService<proto.photobank_user_albums>
	{
		public photobank_user_albumsStore()
		{
			m_Items = new SortedList<long, proto.photobank_user_albums>();
		}
		private SortedList<long, proto.photobank_user_albums> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.photobank_user_albums> GetAll()
		{
			return Queryable.AsQueryable<proto.photobank_user_albums>(All());
		}
		public proto.photobank_user_albums GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.photobank_user_albums>.Insert(proto.photobank_user_albums item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.photobank_user_albums>.Delete(proto.photobank_user_albums item)
		{
			Delete(item);
		}
		public proto.photobank_user_albums CreateItem()
		{
			return new proto.photobank_user_albums() {   };
		}
		public void AbortItem(proto.photobank_user_albums item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.photobank_user_albums>.Update(proto.photobank_user_albums item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.photobank_user_albums);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `title`, `shoot_date` FROM photobank_user_albums");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_user_albums();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.photobank_user_albums Insert(MySqlConnection _connection, proto.photobank_user_albums _item)
		{
			var cmd = new MySqlCommand("INSERT INTO photobank_user_albums ( `account_id`, `title`, `shoot_date` ) VALUES ( @account_id, @title, @shoot_date ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "shoot_date", Value = (_item.shoot_date != null && _item.shoot_date.Year > 1800) ? _item.shoot_date : new DateTime(1800, 1, 1) });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.photobank_user_albums Update(MySqlConnection _connection, proto.photobank_user_albums _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE photobank_user_albums SET `account_id`= @account_id, `title`= @title, `shoot_date`= @shoot_date WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_account_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "account_id = @account_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "account_id", Value = _item.account_id });
			}
			if(_item.mc_title)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "title = @title";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "title", Value = _item.title != null ? (object)_item.title : DBNull.Value });
			}
			if(_item.mc_shoot_date)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "shoot_date = @shoot_date";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "shoot_date", Value = _item.shoot_date });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE photobank_user_albums SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.photobank_user_albums Delete(MySqlConnection _connection, proto.photobank_user_albums _item)
		{
			var cmd = new MySqlCommand("DELETE FROM photobank_user_albums WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.photobank_user_albums Insert(proto.photobank_user_albums _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.photobank_user_albums Persist(proto.photobank_user_albums _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.photobank_user_albums Delete(proto.photobank_user_albums _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.photobank_user_albums Update(proto.photobank_user_albums _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.photobank_user_albums> All()
		{
			return m_Items.Values;
		}
		public proto.photobank_user_albums Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `title`, `shoot_date` FROM photobank_user_albums WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `account_id`, `title`, `shoot_date` FROM photobank_user_albums WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.photobank_user_albums();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
