/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.protoStore
{
	public partial class resumes_entriesStore : Meridian.IEntityStore, admin.db.IDataService<proto.resumes_entries>
	{
		public resumes_entriesStore()
		{
			m_Items = new SortedList<long, proto.resumes_entries>();
		}
		private SortedList<long, proto.resumes_entries> m_Items;
		public void Commit()
		{
			//throw new NotImplementedException();
		}
		public IQueryable<proto.resumes_entries> GetAll()
		{
			return Queryable.AsQueryable<proto.resumes_entries>(All());
		}
		public proto.resumes_entries GetById(long id)
		{
			return Get(id);
		}
		void admin.db.IDataService<proto.resumes_entries>.Insert(proto.resumes_entries item)
		{
			Insert(item);
		}
		void admin.db.IDataService<proto.resumes_entries>.Delete(proto.resumes_entries item)
		{
			Delete(item);
		}
		public proto.resumes_entries CreateItem()
		{
			return new proto.resumes_entries() {   };
		}
		public void AbortItem(proto.resumes_entries item)
		{
			Delete(item);
		}
		public void Discard()
		{
			;
		}
		void admin.db.IDataService<proto.resumes_entries>.Update(proto.resumes_entries item)
		{
			Persist(item);
		}
		public object GetObject(long _id)
		{
			return Get(_id);
		}
		public System.Type GetObjectType()
		{
			return typeof(proto.resumes_entries);
		}
		public void DeleteById(long _id)
		{
			Delete(Get(_id));
		}
		public void UpdateById(long _id)
		{
			Update(Get(_id));
		}
		public void LoadAggregations(Meridian _meridian)
		{
			foreach(var item in m_Items.Values)
			{
				item.LoadAggregations(_meridian);
			}
		}
		public void Select(MySqlConnection _connection)
		{
			var cmd = new MySqlCommand("SELECT `id`, `resume_id`, `resume_entry_id` FROM resumes_entries");
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.resumes_entries();
					item.LoadFromReader(reader);
					m_Items[item.id] = item;
				}
			}
		}
		public proto.resumes_entries Insert(MySqlConnection _connection, proto.resumes_entries _item)
		{
			var cmd = new MySqlCommand("INSERT INTO resumes_entries ( `resume_id`, `resume_entry_id` ) VALUES ( @resume_id, @resume_entry_id ); SELECT LAST_INSERT_ID();"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resume_id", Value = _item.resume_id });
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resume_entry_id", Value = _item.resume_entry_id });
			cmd.Connection = _connection;
			_item.id = Convert.ToInt64(cmd.ExecuteScalar());
			m_Items.Add(_item.id, _item);
			_item.LoadAggregations(Meridian.Default);
			return _item;
		}
		public proto.resumes_entries Update(MySqlConnection _connection, proto.resumes_entries _item)
		{
			bool changed =  false;
			var cmdText =  "";
			var cmd = new MySqlCommand("UPDATE resumes_entries SET `resume_id`= @resume_id, `resume_entry_id`= @resume_entry_id WHERE id=@id"); ;
			if(_item.mc_id)
			{
			}
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			if(_item.mc_resume_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "resume_id = @resume_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resume_id", Value = _item.resume_id });
			}
			if(_item.mc_resume_entry_id)
			{
				changed =  true;
				cmdText += (cmdText.Length > 0 ? ", " : "") + "resume_entry_id = @resume_entry_id";
				cmd.Parameters.Add( new MySqlParameter() { ParameterName = "resume_entry_id", Value = _item.resume_entry_id });
			}
			if(changed)
			{
				cmd.CommandText =  "UPDATE resumes_entries SET " + cmdText + " WHERE id=@id";
				cmd.Connection = _connection;
				cmd.ExecuteNonQuery();
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public proto.resumes_entries Delete(MySqlConnection _connection, proto.resumes_entries _item)
		{
			var cmd = new MySqlCommand("DELETE FROM resumes_entries WHERE id=@id"); ;
			cmd.Parameters.Add( new MySqlParameter() { ParameterName = "id", Value = _item.id });
			cmd.Connection = _connection;
			cmd.ExecuteScalar();
			return _item;
		}
		public proto.resumes_entries Insert(proto.resumes_entries _item)
		{
			MeridianMonitor.Default.MySqlActionForeground((conn) => Insert(conn, _item));;
			return _item;
		}
		public proto.resumes_entries Persist(proto.resumes_entries _item)
		{
			if(_item.id <= 0)
			{
				_item = Insert(_item);
			}
			_item = Update(_item);
			return _item;
		}
		public proto.resumes_entries Delete(proto.resumes_entries _item)
		{
			_item.DeleteCompositions(Meridian.Default);
			_item.DeleteAggregations();
			m_Items.Remove(_item.id);
			MeridianMonitor.Default.MySqlActionBackground((conn) => Delete(conn, _item));;
			return _item;
		}
		public proto.resumes_entries Update(proto.resumes_entries _item)
		{
			MeridianMonitor.Default.MySqlActionBackground((conn) => Update(conn, _item));;
			return _item;
		}
		public IList<proto.resumes_entries> All()
		{
			return m_Items.Values;
		}
		public proto.resumes_entries Get(long _id)
		{
			return m_Items[_id];
		}
		public bool Exists(long _id)
		{
			return m_Items.ContainsKey(_id);
		}
		public void UpdateSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			var cmd = new MySqlCommand("SELECT `id`, `resume_id`, `resume_entry_id` FROM resumes_entries WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					item.DeleteCompositions(Meridian.Default);
					item.DeleteAggregations();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
				}
			}
		}
		public void InsertSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if(Exists(_id)) return;;
			var cmd = new MySqlCommand("SELECT `id`, `resume_id`, `resume_entry_id` FROM resumes_entries WHERE id = " + _id.ToString());
			cmd.Connection = _connection;
			using(var reader = cmd.ExecuteReader())
			{
				while(reader.Read())
				{
					var item = new proto.resumes_entries();
					item.LoadFromReader(reader);
					item.LoadAggregations(_meridian);
					item.LoadCompositions(_meridian);
					m_Items.Add(item.id, item);
				}
			}
		}
		public void DeleteSync(MySqlConnection _connection, long _id, Meridian _meridian)
		{
			if (!Exists(_id))
			{
			return;
			}
			var item = Get(_id);
			item.DeleteCompositions(Meridian.Default);
			item.DeleteAggregations();
			m_Items.Remove(item.id);
		}
	}
}
