/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(blog_photos_meta))]	public partial class blog_photos : admin.db.IDatabaseEntity
	{
		public blog_photos()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private long m_blog_id = 0;
		internal bool mc_blog_id { get; private set; }
		private string m_original = "";
		internal bool mc_original { get; private set; }
		private string m_list_thumbnail = "";
		internal bool mc_list_thumbnail { get; private set; }
		private string m_normal_thumbnail = "";
		internal bool mc_normal_thumbnail { get; private set; }
		private System.Guid m_guid = new System.Guid();
		internal bool mc_guid { get; private set; }
		private string m_alt = "";
		internal bool mc_alt { get; private set; }
		private string m_url = "";
		internal bool mc_url { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_blog_id = _reader["blog_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("blog_id") : 0;
			mc_blog_id = false;
			m_original = _reader["original"].GetType() != typeof(System.DBNull) ? _reader.GetString("original") : "";
			mc_original = false;
			m_list_thumbnail = _reader["list_thumbnail"].GetType() != typeof(System.DBNull) ? _reader.GetString("list_thumbnail") : "";
			mc_list_thumbnail = false;
			m_normal_thumbnail = _reader["normal_thumbnail"].GetType() != typeof(System.DBNull) ? _reader.GetString("normal_thumbnail") : "";
			mc_normal_thumbnail = false;
			m_guid = _reader["guid"].GetType() != typeof(System.DBNull) ? !String.IsNullOrEmpty(_reader["guid"].ToString()) ? _reader.GetGuid("guid") : new System.Guid() : new System.Guid();
			mc_guid = false;
			m_alt = _reader["alt"].GetType() != typeof(System.DBNull) ? _reader.GetString("alt") : "";
			mc_alt = false;
			m_url = _reader["url"].GetType() != typeof(System.DBNull) ? _reader.GetString("url") : "";
			mc_url = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
			if((blog_id > 0) && (_meridian.blogsStore.Exists(blog_id)))
			{
				this.im_blogs_blogs = _meridian.blogsStore.Get(blog_id);;
				this.im_blogs_blogs.AddImagesBlog(this);
			}
		}
		public void DeleteAggregations()
		{
			if(this.im_blogs_blogs != null)
			{
				this.im_blogs_blogs.RemoveImagesBlog(this);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "blog_photos"; }
		}
		/* metafile template 
		internal class blog_photos_meta
		{
			public long id { get; set; }
			public long blog_id { get; set; }
			public string original { get; set; }
			public string list_thumbnail { get; set; }
			public string normal_thumbnail { get; set; }
			public System.Guid guid { get; set; }
			public string alt { get; set; }
			public string url { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public long blog_id
		{
			get
			{
				return m_blog_id;
			}
			set
			{
				if(m_blog_id != value)
				{
					m_blog_id = value != null ? value : 0;
					mc_blog_id = true;
					// call update worker thread;
				}
			}
		}
		public string original
		{
			get
			{
				return m_original;
			}
			set
			{
				if(m_original != value)
				{
					m_original = value != null ? value : "";
					mc_original = true;
					// call update worker thread;
				}
			}
		}
		public string list_thumbnail
		{
			get
			{
				return m_list_thumbnail;
			}
			set
			{
				if(m_list_thumbnail != value)
				{
					m_list_thumbnail = value != null ? value : "";
					mc_list_thumbnail = true;
					// call update worker thread;
				}
			}
		}
		public string normal_thumbnail
		{
			get
			{
				return m_normal_thumbnail;
			}
			set
			{
				if(m_normal_thumbnail != value)
				{
					m_normal_thumbnail = value != null ? value : "";
					mc_normal_thumbnail = true;
					// call update worker thread;
				}
			}
		}
		public System.Guid guid
		{
			get
			{
				return m_guid;
			}
			set
			{
				if(m_guid != value)
				{
					m_guid = value != null ? value : new System.Guid();
					mc_guid = true;
					// call update worker thread;
				}
			}
		}
		public string alt
		{
			get
			{
				return m_alt;
			}
			set
			{
				if(m_alt != value)
				{
					m_alt = value != null ? value : "";
					mc_alt = true;
					// call update worker thread;
				}
			}
		}
		public string url
		{
			get
			{
				return m_url;
			}
			set
			{
				if(m_url != value)
				{
					m_url = value != null ? value : "";
					mc_url = true;
					// call update worker thread;
				}
			}
		}
		private blogs im_blogs_blogs
		{
			get; set; 
		}
		public blogs GetImagesBlogBlog()
		{
			return im_blogs_blogs ;
		}
	}
}
