/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(company_ownerships_meta))]	public partial class company_ownerships : admin.db.IDatabaseEntity
	{
		public company_ownerships()
		{
			ow_companies = new List<companies>();
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "company_ownerships"; }
		}
		/* metafile template 
		internal class company_ownerships_meta
		{
			public long id { get; set; }
			public string title { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		private List<companies> ow_companies
		{
			get; set; 
		}
		[ScriptIgnore]
		public IEnumerable<companies> Companies
		{
			get { return ow_companies; }
		}
		public IEnumerable<companies> GetCompanies()
		{
			return ow_companies;
		}
		public companies AddCompanies(companies _item, bool _insertToStore = false)
		{
			if(ow_companies.IndexOf(_item) != -1) return _item;
			ow_companies.Add(_item);
			_item.ownership_id = id;
			if(_insertToStore && !Meridian.Default.companiesStore.Exists(_item.id))
			{
				Meridian.Default.companiesStore.Insert(_item);
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public companies RemoveCompanies(companies _item, bool _complete = false)
		{
			ow_companies.Remove(_item);
			if(_complete) Meridian.Default.companiesStore.Delete(_item);
			return _item;
		}
	}
}
