/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(quiz_options_meta))]	public partial class quiz_options : admin.db.IDatabaseEntity
	{
		public quiz_options()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private long m_quiz_id = 0;
		internal bool mc_quiz_id { get; private set; }
		private string m_value = "";
		internal bool mc_value { get; private set; }
		private int m_order = 0;
		internal bool mc_order { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_quiz_id = _reader["quiz_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("quiz_id") : 0;
			mc_quiz_id = false;
			m_value = _reader["value"].GetType() != typeof(System.DBNull) ? _reader.GetString("value") : "";
			mc_value = false;
			m_order = _reader["order"].GetType() != typeof(System.DBNull) ? _reader.GetInt32("order") : 0;
			mc_order = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "quiz_options"; }
		}
		/* metafile template 
		internal class quiz_options_meta
		{
			public long id { get; set; }
			public long quiz_id { get; set; }
			public string value { get; set; }
			public int order { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public long quiz_id
		{
			get
			{
				return m_quiz_id;
			}
			set
			{
				if(m_quiz_id != value)
				{
					m_quiz_id = value != null ? value : 0;
					mc_quiz_id = true;
					// call update worker thread;
				}
			}
		}
		public string value
		{
			get
			{
				return m_value;
			}
			set
			{
				if(m_value != value)
				{
					m_value = value != null ? value : "";
					mc_value = true;
					// call update worker thread;
				}
			}
		}
		public int order
		{
			get
			{
				return m_order;
			}
			set
			{
				if(m_order != value)
				{
					m_order = value != null ? value : 0;
					mc_order = true;
					// call update worker thread;
				}
			}
		}
	}
}
