/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(resume_trainings_meta))]	public partial class resume_trainings : admin.db.IDatabaseEntity
	{
		public resume_trainings()
		{
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private DateTime m_begin_date = DateTime.MinValue;
		internal bool mc_begin_date { get; private set; }
		private DateTime m_end_date = DateTime.MinValue;
		internal bool mc_end_date { get; private set; }
		private string m_description = "";
		internal bool mc_description { get; private set; }
		private long m_resume_id = 0;
		internal bool mc_resume_id { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_begin_date = _reader["begin_date"].GetType() != typeof(System.DBNull) ? _reader.GetDateTime("begin_date") : DateTime.MinValue;
			mc_begin_date = false;
			m_end_date = _reader["end_date"].GetType() != typeof(System.DBNull) ? _reader.GetDateTime("end_date") : DateTime.MinValue;
			mc_end_date = false;
			m_description = _reader["description"].GetType() != typeof(System.DBNull) ? _reader.GetString("description") : "";
			mc_description = false;
			m_resume_id = _reader["resume_id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("resume_id") : 0;
			mc_resume_id = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
			if((resume_id > 0) && (_meridian.resumesStore.Exists(resume_id)))
			{
				this.re_trainings_resumes = _meridian.resumesStore.Get(resume_id);;
				this.re_trainings_resumes.AddTrainings(this);
			}
		}
		public void DeleteAggregations()
		{
			if(this.re_trainings_resumes != null)
			{
				this.re_trainings_resumes.RemoveTrainings(this);
			}
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "resume_trainings"; }
		}
		/* metafile template 
		internal class resume_trainings_meta
		{
			public long id { get; set; }
			public DateTime begin_date { get; set; }
			public DateTime end_date { get; set; }
			public string description { get; set; }
			public long resume_id { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public DateTime begin_date
		{
			get
			{
				return m_begin_date;
			}
			set
			{
				if(m_begin_date != value)
				{
					m_begin_date = value != null ? value : DateTime.MinValue;
					if(m_begin_date.Year < 1800) value = DateTime.MinValue;
					mc_begin_date = true;
					// call update worker thread;
				}
			}
		}
		public DateTime end_date
		{
			get
			{
				return m_end_date;
			}
			set
			{
				if(m_end_date != value)
				{
					m_end_date = value != null ? value : DateTime.MinValue;
					if(m_end_date.Year < 1800) value = DateTime.MinValue;
					mc_end_date = true;
					// call update worker thread;
				}
			}
		}
		public string description
		{
			get
			{
				return m_description;
			}
			set
			{
				if(m_description != value)
				{
					m_description = value != null ? value : "";
					mc_description = true;
					// call update worker thread;
				}
			}
		}
		public long resume_id
		{
			get
			{
				return m_resume_id;
			}
			set
			{
				if(m_resume_id != value)
				{
					m_resume_id = value != null ? value : 0;
					mc_resume_id = true;
					// call update worker thread;
				}
			}
		}
		private resumes re_trainings_resumes
		{
			get; set; 
		}
		public resumes GetTrainingsResume()
		{
			return re_trainings_resumes ;
		}
	}
}
