/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(sale_types_meta))]	public partial class sale_types : admin.db.IDatabaseEntity
	{
		public sale_types()
		{
			st_sales = new List<sales>();
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		private bool m_unlimited = false;
		internal bool mc_unlimited { get; private set; }
		private int m_order = 0;
		internal bool mc_order { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
			m_unlimited = _reader["unlimited"].GetType() != typeof(System.DBNull) ? _reader.GetBoolean("unlimited") : false;
			mc_unlimited = false;
			m_order = _reader["order"].GetType() != typeof(System.DBNull) ? _reader.GetInt32("order") : 0;
			mc_order = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "sale_types"; }
		}
		/* metafile template 
		internal class sale_types_meta
		{
			public long id { get; set; }
			public string title { get; set; }
			public bool unlimited { get; set; }
			public int order { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		public bool unlimited
		{
			get
			{
				return m_unlimited;
			}
			set
			{
				if(m_unlimited != value)
				{
					m_unlimited = value != null ? value : false;
					mc_unlimited = true;
					// call update worker thread;
				}
			}
		}
		public int order
		{
			get
			{
				return m_order;
			}
			set
			{
				if(m_order != value)
				{
					m_order = value != null ? value : 0;
					mc_order = true;
					// call update worker thread;
				}
			}
		}
		private List<sales> st_sales
		{
			get; set; 
		}
		[ScriptIgnore]
		public IEnumerable<sales> SaleType
		{
			get { return st_sales; }
		}
		public IEnumerable<sales> GetSaleType()
		{
			return st_sales;
		}
		public sales AddSaleType(sales _item, bool _insertToStore = false)
		{
			if(st_sales.IndexOf(_item) != -1) return _item;
			st_sales.Add(_item);
			_item.sale_type_id = id;
			if(_insertToStore && !Meridian.Default.salesStore.Exists(_item.id))
			{
				Meridian.Default.salesStore.Insert(_item);
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public sales RemoveSaleType(sales _item, bool _complete = false)
		{
			st_sales.Remove(_item);
			if(_complete) Meridian.Default.salesStore.Delete(_item);
			return _item;
		}
	}
}
