/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Script.Serialization;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;

namespace meridian.smolensk.proto
{
	[MetadataType(typeof(vacancy_entry_categories_meta))]	public partial class vacancy_entry_categories : admin.db.IDatabaseEntity
	{
		public vacancy_entry_categories()
		{
			va_ca_entries = new List<vacancy_entries>();
		}
		private long m_id = 0;
		internal bool mc_id { get; private set; }
		private string m_title = "";
		internal bool mc_title { get; private set; }
		public void LoadFromReader(MySqlDataReader _reader)
		{
			m_id = _reader["id"].GetType() != typeof(System.DBNull) ? _reader.GetInt64("id") : 0;
			mc_id = false;
			m_title = _reader["title"].GetType() != typeof(System.DBNull) ? _reader.GetString("title") : "";
			mc_title = false;
		}
		public void LoadAggregations(Meridian _meridian)
		{
		}
		public void DeleteAggregations()
		{
		}
		public void LoadCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public void SaveCompositions(Meridian _meridian)
		{
		}
		public void DeleteCompositions(Meridian _meridian)
		{
			string[] keyIds = null;
		}
		public string ProtoName
		{
			get { return "vacancy_entry_categories"; }
		}
		/* metafile template 
		internal class vacancy_entry_categories_meta
		{
			public long id { get; set; }
			public string title { get; set; }
		}
		 metafile template */
		public long id
		{
			get
			{
				return m_id;
			}
			set
			{
				if(m_id != value)
				{
					m_id = value != null ? value : 0;
					mc_id = true;
					// call update worker thread;
				}
			}
		}
		public string title
		{
			get
			{
				return m_title;
			}
			set
			{
				if(m_title != value)
				{
					m_title = value != null ? value : "";
					mc_title = true;
					// call update worker thread;
				}
			}
		}
		private List<vacancy_entries> va_ca_entries
		{
			get; set; 
		}
		[ScriptIgnore]
		public IEnumerable<vacancy_entries> Entries
		{
			get { return va_ca_entries; }
		}
		public IEnumerable<vacancy_entries> GetEntries()
		{
			return va_ca_entries;
		}
		public vacancy_entries AddEntries(vacancy_entries _item, bool _insertToStore = false)
		{
			if(va_ca_entries.IndexOf(_item) != -1) return _item;
			va_ca_entries.Add(_item);
			_item.vacancy_entry_category_id = id;
			if(_insertToStore && !Meridian.Default.vacancy_entriesStore.Exists(_item.id))
			{
				Meridian.Default.vacancy_entriesStore.Insert(_item);
				_item.LoadAggregations(Meridian.Default);
			}
			return _item;
		}
		public vacancy_entries RemoveEntries(vacancy_entries _item, bool _complete = false)
		{
			va_ca_entries.Remove(_item);
			if(_complete) Meridian.Default.vacancy_entriesStore.Delete(_item);
			return _item;
		}
	}
}
