/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;
using meridian.smolensk.proto;
using admin.web.common;

namespace meridian.smolensk.controller
{
	public partial class meridian_photobank_licenses : BaseUniversalController<photobank_licenses>
	{
		public meridian_photobank_licenses()
		{
		}
		protected override admin.db.IDataService<photobank_licenses> GetService()
		{
			return Meridian.Default.photobank_licensesStore;
		}
	}
}
