/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using meridian.smolensk;
using meridian.smolensk.system;
using meridian.smolensk.proto;
using admin.web.common;

namespace meridian.smolensk.controller
{
	public partial class meridian_city_prices_icons : BaseUniversalController<city_prices_icons>
	{
		public meridian_city_prices_icons()
		{
		}
		protected override admin.db.IDataService<city_prices_icons> GetService()
		{
			return Meridian.Default.city_prices_iconsStore;
		}
	}
}
