SET NAMES utf8;

INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('15', 'Тип предложения', '2');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('16', 'Тип предложения', '3');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('17', 'Тип предложения', '5');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('18', 'Тип предложения', '6');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('19', 'Тип предложения', '7');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('20', 'Тип предложения', '8');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('21', 'Тип предложения', '9');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('22', 'Тип предложения', '10');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('23', 'Тип предложения', '11');
INSERT INTO `smolensk`.`ad_field_descriptions` (`id`, `title`, `ad_category_id`) VALUES ('24', 'Тип предложения', '13');

INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Вязка');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Найден');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('15', 'Потерян');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('16', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('16', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('16', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('16', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('16', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('17', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('17', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('17', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('17', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('17', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('18', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('18', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('18', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('18', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('18', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('19', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('19', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('19', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('19', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('19', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('20', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('20', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('20', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('20', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('20', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('21', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('21', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('21', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('21', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('21', 'Аренда');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('22', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('22', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('22', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('22', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('23', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('23', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('23', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('23', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('24', 'Куплю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('24', 'Продам');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('24', 'Обменяю');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('24', 'Даром');
INSERT INTO `smolensk`.`ad_lookup_values` (`description_id`, `value`) VALUES ('24', 'Аренда');
