/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class ad_advert_requests_meta
	{
		public ad_advert_requests_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long account_id { get; set; }
		public long ad_id { get; set; }
		public bool in_interesting { get; set; }
		public bool pin_to_list { get; set; }
		/* metafile template */
	}
}
