/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class company_photos_meta
	{
		public company_photos_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public string thumbnaill { get; set; }
		public string normal { get; set; }
		public bool is_main { get; set; }
		public long company_id { get; set; }
		/* metafile template */
	}
}
