/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class photobank_photo_prices_meta
	{
		public photobank_photo_prices_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long rel_photo_id { get; set; }
		public int license_id { get; set; }
		public double price { get; set; }
		/* metafile template */
	}
}
