/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class restaurants_reserve_meta
	{
		public restaurants_reserve_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public DateTime create_date { get; set; }
		public string contact { get; set; }
		public string phone { get; set; }
		public DateTime visit_date { get; set; }
		public int persons_count { get; set; }
		public long account_id { get; set; }
		public long restaraunt_id { get; set; }
		/* metafile template */
	}
}
