/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class restaurants_entries_meta
	{
		public restaurants_entries_meta()
		{
		}
		/* metafile template */
		public long restaurant_id { get; set; }
		public long entry_id { get; set; }
		public long id { get; set; }
		/* metafile template */
	}
}
