/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class resume_works_meta
	{
		public resume_works_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public DateTime begin_date { get; set; }
		public DateTime end_date { get; set; }
		public string post { get; set; }
		public int work_time_id { get; set; }
		public string company_name { get; set; }
		public string success_description { get; set; }
		public long resume_id { get; set; }
		/* metafile template */
	}
}
