/* Automatically generated codefile, Meridian
 * Generated by magic, please do not interfere
 * Please sleep well and do not smoke. Love, Sam */

using System;
using System.Linq;
using System.Text;
using System.Data.Linq;
using System.Collections.Generic;

namespace meridian.smolensk.proto
{
	public partial class vacancies_professionals_meta
	{
		public vacancies_professionals_meta()
		{
		}
		/* metafile template */
		public long id { get; set; }
		public long vacancy_id { get; set; }
		public long professional_id { get; set; }
		/* metafile template */
	}
}
